version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.10
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
